routes:

    home:
        pattern: /
        controller: controller.helloworld
        action: sayHello
        methods:
          - GET

    show_your_name:
        pattern: /{yourName}
        controller: controller.helloworld
        action: sayYourName
        rules:
            yourName: "[a-zA-Z]+"
        methods:
          - GET